"""Neural CML components for continuous-control MuJoCo tasks.

The model keeps the CML idea that actions are latent-space displacements, while
adding neural encoders and a small residual transition model.

Author: generated by ChatGPT
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Tuple

import torch
from torch import nn
import torch.nn.functional as F


def mlp(input_dim: int, hidden_dim: int, output_dim: int, depth: int = 2) -> nn.Sequential:
    """Build a simple MLP with LayerNorm for stable latent prediction."""
    layers = []
    last_dim = input_dim
    for _ in range(depth):
        layers += [
            nn.Linear(last_dim, hidden_dim),
            nn.LayerNorm(hidden_dim),
            nn.SiLU(),
        ]
        last_dim = hidden_dim
    layers.append(nn.Linear(last_dim, output_dim))
    return nn.Sequential(*layers)


@dataclass
class CMLLossOutput:
    total: torch.Tensor
    pred: torch.Tensor
    recon: torch.Tensor
    action_norm: torch.Tensor
    residual_norm: torch.Tensor


class NeuralCML(nn.Module):
    """CML-style latent dynamics model.

    For observation o_t and action a_t:

        s_t = encoder(o_t)
        action_delta_t = action_encoder(a_t)
        s_next_hat = s_t + action_delta_t + residual([s_t, a_t])

    An observation decoder is included only as a representation regularizer, so
    the encoder does not collapse into a latent space that predicts transitions
    but forgets useful state information.
    """

    def __init__(
        self,
        obs_dim: int,
        action_dim: int,
        latent_dim: int = 128,
        hidden_dim: int = 256,
        depth: int = 2,
    ) -> None:
        super().__init__()
        self.obs_dim = obs_dim
        self.action_dim = action_dim
        self.latent_dim = latent_dim

        self.encoder = mlp(obs_dim, hidden_dim, latent_dim, depth)
        self.decoder = mlp(latent_dim, hidden_dim, obs_dim, depth)
        self.action_encoder = mlp(action_dim, hidden_dim, latent_dim, depth)
        self.residual = mlp(latent_dim + action_dim, hidden_dim, latent_dim, depth)

        # Keep the initial residual small so the model starts close to the
        # original CML assumption: next latent ~= current latent + action vector.
        final = self.residual[-1]
        if isinstance(final, nn.Linear):
            nn.init.zeros_(final.weight)
            nn.init.zeros_(final.bias)

    def encode(self, obs: torch.Tensor) -> torch.Tensor:
        return self.encoder(obs)

    def decode(self, state: torch.Tensor) -> torch.Tensor:
        return self.decoder(state)

    def action_delta(self, action: torch.Tensor) -> torch.Tensor:
        return self.action_encoder(action)

    def transition(self, state: torch.Tensor, action: torch.Tensor) -> torch.Tensor:
        residual_in = torch.cat([state, action], dim=-1)
        return state + self.action_delta(action) + self.residual(residual_in)

    def forward(self, obs: torch.Tensor, action: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
        state = self.encode(obs)
        next_state_hat = self.transition(state, action)
        return state, next_state_hat

    def loss(
        self,
        obs: torch.Tensor,
        action: torch.Tensor,
        next_obs: torch.Tensor,
        pred_weight: float = 1.0,
        recon_weight: float = 0.05,
        action_norm_weight: float = 1e-4,
        residual_norm_weight: float = 1e-3,
    ) -> CMLLossOutput:
        state, next_state_hat = self.forward(obs, action)
        with torch.no_grad():
            next_state_target = self.encode(next_obs)

        # Prediction learning objective.
        pred = F.mse_loss(next_state_hat, next_state_target)

        # Reconstruction regularizer keeps latent states informative.
        obs_hat = self.decode(state)
        next_obs_hat = self.decode(next_state_hat)
        recon = 0.5 * F.mse_loss(obs_hat, obs) + 0.5 * F.mse_loss(next_obs_hat, next_obs)

        # Regularizers keep the geometry from becoming too distorted.
        action_delta = self.action_delta(action)
        residual_in = torch.cat([state, action], dim=-1)
        residual_delta = self.residual(residual_in)
        action_norm = action_delta.pow(2).mean()
        residual_norm = residual_delta.pow(2).mean()

        total = (
            pred_weight * pred
            + recon_weight * recon
            + action_norm_weight * action_norm
            + residual_norm_weight * residual_norm
        )
        return CMLLossOutput(total, pred, recon, action_norm, residual_norm)


@torch.no_grad()
def sample_action_sequences(
    action_low: torch.Tensor,
    action_high: torch.Tensor,
    num_sequences: int,
    horizon: int,
    action_dim: int,
    device: torch.device,
) -> torch.Tensor:
    """Uniformly sample candidate action sequences inside environment bounds."""
    shape = (num_sequences, horizon, action_dim)
    u = torch.rand(shape, device=device)
    return action_low + u * (action_high - action_low)


@torch.no_grad()
def plan_action_random_shooting(
    model: NeuralCML,
    obs: torch.Tensor,
    goal_obs: torch.Tensor,
    action_low: torch.Tensor,
    action_high: torch.Tensor,
    num_sequences: int = 1024,
    horizon: int = 8,
    action_cost: float = 0.001,
) -> torch.Tensor:
    """Choose an action using short-horizon latent CML planning.

    The score is high when the predicted latent state approaches the goal
    latent state. This is the multi-step version of the CML utility
    dot(goal - state, action_delta), adapted to continuous actions.
    """
    device = obs.device
    action_dim = action_low.shape[-1]

    obs_batch = obs.unsqueeze(0).repeat(num_sequences, 1)
    goal_batch = goal_obs.unsqueeze(0).repeat(num_sequences, 1)

    state = model.encode(obs_batch)
    goal_state = model.encode(goal_batch)
    actions = sample_action_sequences(
        action_low=action_low,
        action_high=action_high,
        num_sequences=num_sequences,
        horizon=horizon,
        action_dim=action_dim,
        device=device,
    )

    total_action_cost = torch.zeros(num_sequences, device=device)
    for t in range(horizon):
        a_t = actions[:, t, :]
        state = model.transition(state, a_t)
        total_action_cost += a_t.pow(2).mean(dim=-1)

    latent_distance = (state - goal_state).pow(2).mean(dim=-1)
    score = -latent_distance - action_cost * total_action_cost
    best = torch.argmax(score)
    return actions[best, 0, :]
